/**
 * @typedef {Object} TranscriptSegment
 * @property {string} text - The text content of the subtitle segment.
 * @property {number} start - The start time in seconds.
 * @property {number} duration - The duration in seconds.
 */

/**
 * @typedef {Object} TranscriptResult
 * @property {string} language - The language code (e.g., 'en').
 * @property {boolean} autoGenerated - Whether the transcript was auto-generated.
 * @property {TranscriptSegment[]} segments - The subtitle segments.
 */

module.exports = {};
