const assert = require('assert');
const subtitleService = require('../electron/subtitles/subtitle-service');
const { SubtitleProvider } = require('../electron/subtitles/provider-interface');

// Create mock providers
class MockSuccessProvider extends SubtitleProvider {
  get name() { return 'mock-success'; }
  async getTranscript(videoId) {
    return {
      language: 'en',
      autoGenerated: true,
      segments: [{ text: 'Hello', start: 0, duration: 1 }]
    };
  }
}

class MockFailProvider extends SubtitleProvider {
  get name() { return 'mock-fail'; }
  async getTranscript(videoId) {
    throw new Error('Simulated failure');
  }
}

async function runTests() {
  console.log('Running subtitle-service tests...');

  // Test 1: Fallback chain success
  try {
    const originalProviders = subtitleService.providers;
    
    // Inject mock providers
    subtitleService.providers = [
      new MockFailProvider(),
      new MockFailProvider(),
      new MockSuccessProvider()
    ];

    const result = await subtitleService.getSubtitles('test_video_id');
    assert.strictEqual(result.segments[0].text, 'Hello', 'Should return success from 3rd provider');
    console.log('✅ Test 1 Passed: Fallback chain works');

    // Restore original providers
    subtitleService.providers = originalProviders;
  } catch (err) {
    console.error('❌ Test 1 Failed:', err);
    process.exit(1);
  }

  // Test 2: Fallback chain complete failure
  try {
    const originalProviders = subtitleService.providers;
    
    subtitleService.providers = [
      new MockFailProvider(),
      new MockFailProvider()
    ];

    let threwError = false;
    try {
      await subtitleService.getSubtitles('test_video_id');
    } catch (e) {
      threwError = true;
      assert(e.message.includes('All subtitle providers failed'), 'Error message should indicate all failed');
    }
    
    assert.strictEqual(threwError, true, 'Should throw an error when all providers fail');
    console.log('✅ Test 2 Passed: Full failure handled correctly');

    // Restore original providers
    subtitleService.providers = originalProviders;
  } catch (err) {
    console.error('❌ Test 2 Failed:', err);
    process.exit(1);
  }

  // Real Integration test (optional, we could skip it or run it on a known video)
  // Let's try one of the actual providers to ensure the deps are wired correctly.
  console.log('\nTesting real provider (youtube-transcript):');
  try {
    const realProvider = subtitleService.providers.find(p => p.name === 'youtube-transcript');
    if (realProvider) {
      // Never Gonna Give You Up
      const res = await realProvider.getTranscript('dQw4w9WgXcQ'); 
      assert(res.segments.length > 0, 'Should return actual segments');
      console.log('✅ Real Provider Test Passed (youtube-transcript)');
    }
  } catch (err) {
    console.log('⚠️ Real Provider Test Failed (could be network or video restriction):', err.message);
  }

  console.log('\nAll tests completed.');
}

runTests();
